### ISSUE TITLE
otagrum installation

### ISSUE THREAD

**Issue by laurent101** [openturns/otagrum#56]
Hello, I'd like to install this OT module on both OSX and Debian (without Conda). Unfortunately, my attempts to install the module following the instructions provided on the OT page have failed so far. Thank you for your assistance.

**Comment by jschueller** [comment]
Hello, unfortunately otagrum is in development and hasnt seen a release so far (it will for openturns 1.15 this spring), so you'll have to compile everything yourself.
On debian you can at least reuse the libopenturns-dev package.on osx you will have to compile from source: http://openturns.github.io/openturns/latest/install.html#from-sources.
Then do the same for agrum (see also https://gitlab.com/agrumery/aGrUM#act-agrum-compilation-tool)
Finally grab the sources of otagrum, and run cmake with OpenTURNS_DIR and aGrUM_DIR variables to the path of the cmake config files.
Take care to configure using the same python version everywhere.

**Comment by laurent101** [comment]
Hi Julien,

many thanks for your assistance. This is very helpful.

Best,
Laurent

**Comment by jschueller** [comment]
Hello @regislebrun @phwuil.
Is the phwuil branch ready to be integrated into master for ?
I see the 2 commits might fix some bugs.

**Comment by jschueller** [comment]
0.2 is out, debian packages should be available soon

**Comment by jschueller** [comment]
@laurent101 conda packages of otagrum 0.2 are available on all platforms, plus the debian packages

**Comment by laurent101** [comment]
Thank you!
