### ISSUE TITLE
problème import pyagrum 20.3 et otagrum 0.4

### ISSUE THREAD

**Issue by cbaudrit** [openturns/otagrum#79]
Bonjour,

Je suis sous windows 10 et j'ai installé anaconda 64bits. Voici mon problème:

Quand je me créé un environnement avec anaconda avec python 3.8, pyagrum 0.18.3 et otagrum 0.3 pas de problème, les import de pyagrum et otagrum fonctionnent.

En revanche dès que j'installe otagrum à 0.4 et pyagrum 20.3 à l'aide du navigateur anaconda ou avec les commandes conda ... quand je fais un

import pyagrum (c'est ok)

import otagrum (il ya un pb dll)

File
"C:\Users\cbaudrit\anaconda3\lib\site-packages\otagrum\__init__.py",
line 18, in <module>
    from .otagrum import *
  File
"C:\Users\cbaudrit\anaconda3\lib\site-packages\otagrum\otagrum.py",
line 15, in <module>
    from . import _otagrum
ImportError: DLL load failed while importing _otagrum: La procédure
spécifiée est introuvable.

**Comment by jschueller** [comment]
oui otagrum est compilé, et toutes les combinaisons de version ne sont pas sensées fonctionner, avec la 20.2 ça devrait marcher

**Comment by jschueller** [comment]
j'ai mis à jour le paquet pour tirer la bonne version de pyagrum
